language: cpp
sudo: required
dist: trusty


services:
    - docker
    
before_script:
    - docker run --name build -i -d -v"$PWD:/src" eugenwintersberger/debian_9:latest
    - docker exec -it build ls
    
script:
    - docker exec -it build ls
    
after_script:
    - docker container stop build
    
