# Site settings
title: libpnicore
email: jan.kotanski@desy.de
description: "libpnicore"
# baseurl: ""
# url: "http://yourdomain.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# markdown: kramdown
# permalink: pretty

include: ['_sources', '_static', '_images', 'api_doc', 'user_guide']
